# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  app:
    build:
      dockerfile: infrastructure/docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/code
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${SHARED_DIR}/result:/usr/share/nginx/html:ro