# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  app:
    build:
      dockerfile_inline: |
        FROM debian:trixie-slim AS base
        RUN apt update
        RUN apt install -y curl nodejs
        RUN apt clean

        # install miniforge (conda alternative) https://github.com/conda-forge/miniforge
        RUN wget -O /Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
        RUN bash /Miniforge3.sh -b -p "/conda"
        RUN rm /Miniforge3.sh

        # Setup python environment
        RUN source "/conda/etc/profile.d/conda.sh"
        RUN conda activate
        COPY ./src/requirements.txt .
        RUN conda create --name tf -y -f requirements.txt
        RUN conda activate tf
        

        #RUN python3 -m venv /venv
        #RUN source /venv/bin/activate
        #RUN pip install --no-cache-dir -r reqiurements.txt
        #
        #RUN apt remove -y build-essential python3-dev
    working_dir: /code
    tty: true
