FROM maven:3-jdk-8-alpine

RUN apk add --no-cache xmlstarlet git openssh-client gawk postgresql-client coreutils

COPY docker/entrypoint-java.sh /entrypoint-java.sh

ENTRYPOINT [ "/entrypoint-java.sh" ]
