{{/*
SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
SPDX-License-Identifier: AGPL-3.0-or-later
*/}}

{{- if .Values.envSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env-secret
  labels:
    {{- include "pollution-v2.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.envSecret }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
