# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0



services:
  importer:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./links:/links
    command: |
        shp2pgsql -s 4326 links/LinkStationsGeometries.shp elaboration.bluetoothlinks_tmp | psql -U bdp -d bdp
        psql -U bdp -d bdp -c "set search_path=public,intimev2,elaboration;update edge as e set linegeometry = tmp.geom from ( select s.id,ST_TRANSFORM(ST_LineMerge(t.geom),25832) as geom from elaboration.bluetoothlinks_tmp t join intimev2.station s on t.id=s.id) as tmp where tmp.id=e.edge_data_id;"
        psql -U bdp -d bdp -c "drop table elaboration.bluetoothlinks_tmp;"
