name: CI/CD parking-forecast

on:
  push:
    paths:
      - "parking-forecast/**"
      - ".github/workflows/ci-parking-forecast.yml"
      - "!*.md"

env:
  WORKING_DIRECTORY: parking-forecast
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/odh-mobility-el-parking-forecast
  PROJECT_NAME: odh-mobility-el-parking-forecast
  DOCKER_TAG: ${{ github.sha }}

jobs:
  # Deploy Test
  deploy-test-parking-forecast:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/feat/parking-forecast'
    concurrency: deploy-test-parking-forecast
    steps:
      - name: Checkout source code
        uses: noi-techpark/github-actions/checkout@v2

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          # General deployment options
          X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          X_DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          X_DOCKER_TAG: ${{ env.DOCKER_TAG }}
          X_RUN_IMMEDIATELY: true
          X_CRON_TRAIN: "0 1 * * *"
          X_CRON_PREDICT: "0 4-23 * * *"
          X_OAUTH_CLIENT_ID: el-parking-forcast
          X_OAUTH_CLIENT_SECRET: ${{ secrets.PARKING_FORECAST_CLIENT_SECRET}}
          X_SHARED_DIR: /var/docker/${{ env.PROJECT_NAME }}/shared
          X_NGINX_PORT: 1006


      - name: Build and push images
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy application
        uses: noi-techpark/github-actions/docker-deploy@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure/ansible
          hosts: 'test'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          docker-username: 'noi-techpark-bot'
          docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          project-name: ${{ env.PROJECT_NAME }}

  # Deploy Prod
  # deploy-prod-parking-forecast:
  #   runs-on: ubuntu-24.04
  #   if: github.ref == 'refs/heads/prod'
  #   concurrency: deploy-prod-parking-forecast
  #   env:
  #     KEYCLOAK_URL: https://auth.opendatahub.com
  #     DOCKER_IMAGE: ghcr.io/${{ github.repository }}/odh-mobility-el-parking-forecast-prod
  #     DOCKER_TAG: ${{ github.sha }}-prod
  #     PROJECT_NAME: odh-mobility-el-parking-forecast-prod
  #   steps:
  #     - name: Checkout source code
  #       uses: noi-techpark/github-actions/checkout@v2
  #     - name: Create .env file
  #       uses: noi-techpark/github-actions/env-file@v2
  #       with:
  #         working-directory: ${{ env.WORKING_DIRECTORY }}
  #       env:
  #         # General deployment options
  #         X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
  #         X_DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
  #         X_DOCKER_TAG: ${{ env.DOCKER_TAG }}

  #     - name: Build and push images
  #       uses: noi-techpark/github-actions/docker-build-and-push@v2
  #       with:
  #         working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
  #         docker-username: ${{ github.actor }}
  #         docker-password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Deploy application
  #       uses: noi-techpark/github-actions/docker-deploy@v2
  #       with:
  #         working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure/ansible
  #         hosts: 'prod'
  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         docker-username: 'noi-techpark-bot'
  #         docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  #         project-name: ${{ env.PROJECT_NAME }}

